import os
os.system('pip install json')
os.system('pip install requests')
os.system('pip install splunk-sdk')
os.system('pip install pymssql')
os.system('pip install PyMySQL')
os.system('pip install pandas')
os.system('pip install paramiko')
os.system('pip install random2')
os.system('pip install matplotlib')
os.system('pip install matplotlib')
os.system('pip install scipy')
os.system('pip install numpy')
os.system('pip install nltk')
os.system('pip install regex')
os.system('pip install decimal')
